builds:
  - binary: saw
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archive:
  format: tar.gz
  files:
    - LICENSE

brew:
  name: saw

  github:
    owner: TylerBrock
    name: homebrew-saw

  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

  commit_author:
    name: TylerBrock
    email: tyler.brock@gmail.com

  folder: Formula
  homepage: "https://github.com/TylerBrock/saw"
  description: "Fast, multipurpose tool for AWS CloudWatch Logs"

git:
  short_hash: true

  #nfpm:
  #  vendor: Tyler Brock
  #  homepage: https://github.com/TylerBrock/saw
  #  maintainer: Tyler Brock <tyler.brock@gmail.com>
  #  description: Fast, multipurpose tool for AWS CloudWatch Logs
  #  license: MIT
  #  formats:
  #    - deb
  #    - rpm
